export type ErrorCode =
  | 'INVALID_HELLO'
  | 'UNSUPPORTED_VERSION'
  | 'ROOM_FULL'
  | 'ROOM_NOT_FOUND'
  | 'ROOM_ALREADY_EXISTS'
  | 'OVER_CAPACITY'
  | 'RATE_LIMITED'
  | 'MESSAGE_TOO_LARGE'
  | 'INVALID_PAYLOAD'
  | 'BAD_STATE'
  | 'HELLO_TIMEOUT'
  | 'MODE_MISMATCH'
  | 'INTERNAL';

export const ERROR_INVALID_HELLO = 0x01;
export const ERROR_UNSUPPORTED_VERSION = 0x02;
export const ERROR_ROOM_FULL = 0x03;
export const ERROR_ROOM_NOT_FOUND = 0x04;
export const ERROR_ROOM_ALREADY_EXISTS = 0x05;
export const ERROR_OVER_CAPACITY = 0x06;
export const ERROR_RATE_LIMITED = 0x07;
export const ERROR_MESSAGE_TOO_LARGE = 0x08;
export const ERROR_INVALID_PAYLOAD = 0x09;
export const ERROR_BAD_STATE = 0x0a;
export const ERROR_HELLO_TIMEOUT = 0x0b;
export const ERROR_MODE_MISMATCH = 0x0c;
export const ERROR_INTERNAL = 0xff;

const BYTE_BY_ERROR: Readonly<Record<ErrorCode, number>> = {
  INVALID_HELLO: ERROR_INVALID_HELLO,
  UNSUPPORTED_VERSION: ERROR_UNSUPPORTED_VERSION,
  ROOM_FULL: ERROR_ROOM_FULL,
  ROOM_NOT_FOUND: ERROR_ROOM_NOT_FOUND,
  ROOM_ALREADY_EXISTS: ERROR_ROOM_ALREADY_EXISTS,
  OVER_CAPACITY: ERROR_OVER_CAPACITY,
  RATE_LIMITED: ERROR_RATE_LIMITED,
  MESSAGE_TOO_LARGE: ERROR_MESSAGE_TOO_LARGE,
  INVALID_PAYLOAD: ERROR_INVALID_PAYLOAD,
  BAD_STATE: ERROR_BAD_STATE,
  HELLO_TIMEOUT: ERROR_HELLO_TIMEOUT,
  MODE_MISMATCH: ERROR_MODE_MISMATCH,
  INTERNAL: ERROR_INTERNAL,
};

const ERROR_BY_BYTE: Readonly<Record<number, ErrorCode>> = {
  [ERROR_INVALID_HELLO]: 'INVALID_HELLO',
  [ERROR_UNSUPPORTED_VERSION]: 'UNSUPPORTED_VERSION',
  [ERROR_ROOM_FULL]: 'ROOM_FULL',
  [ERROR_ROOM_NOT_FOUND]: 'ROOM_NOT_FOUND',
  [ERROR_ROOM_ALREADY_EXISTS]: 'ROOM_ALREADY_EXISTS',
  [ERROR_OVER_CAPACITY]: 'OVER_CAPACITY',
  [ERROR_RATE_LIMITED]: 'RATE_LIMITED',
  [ERROR_MESSAGE_TOO_LARGE]: 'MESSAGE_TOO_LARGE',
  [ERROR_INVALID_PAYLOAD]: 'INVALID_PAYLOAD',
  [ERROR_BAD_STATE]: 'BAD_STATE',
  [ERROR_HELLO_TIMEOUT]: 'HELLO_TIMEOUT',
  [ERROR_MODE_MISMATCH]: 'MODE_MISMATCH',
  [ERROR_INTERNAL]: 'INTERNAL',
};

export const errorCodeToByte = (code: ErrorCode): number => BYTE_BY_ERROR[code];

export const byteToErrorCode = (byte: number): ErrorCode | undefined => ERROR_BY_BYTE[byte];
